examen/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuario/', include('usuario.urls')),
    path('home/', include('hule.urls')),
]

hule/urls.py
from django.urls import path
from hule import views


app_name = 'hule'


urlpatterns = [
    path('home/<int:usuario_id>/', views.home, name='home'), # ve todas sus fincas que le corresponden

    path('crear/<int:usuario_id>/', views.crear_finca, name='crear_finca'),     # crea una su finquita
    path('editar/<int:finca_id>/', views.editar_finca, name='editar_finca'),    # edita su finquita
    path('borrar/<int:finca_id>/', views.borrar_finca, name='borrar_finca'),    # elimina su finquita

    path('home-p/<int:usuario_id>/', views.home_parcelas, name='home_parcelas'),    # ve todas sus parcelas
    path('ver/<int:usuario_id>/<int:finca_id>/', views.ver_parcela_de_finca, name='ver_parcela'),   # ver parcelas
    path('crear-p/<int:usuario_id>/<int:finca_id>/', views.nueva_parcela, name='crear_parcela'),    # crear parcela
    path('editar-p/<int:usuario_id>/<int:finca_id>/', views.editar_parcela, name='editar_parcela'),    # crear parcela

    path('arboles/', views.arboles, name='arboles'),
]

usuario/urls.py
from django.urls import path
from usuario import views


app_name = 'usuario'


urlpatterns = [
    path('registro/', views.crear_usuario, name='registro'),
    path('inicio/', views.inicio_sesion, name='inicio'),
]

hule/models.py
from django.db import models
from usuario.models import Usuario


# Create your models here.
class Finca(models.Model):
    nombre = models.CharField(max_length=50)
    pais = models.CharField(max_length=50)
    departamento = models.CharField(max_length=50)
    propietario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='propietario')

    def __str__(self):
        return self.nombre


class Parcela(models.Model):
    finca_origen = models.ForeignKey(Finca, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)
    latitud = models.CharField(max_length=50)
    longitud = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre


class Tree(models.Model):  # * Solo pueden haber 10 arboles por parcela por año
    parcela_origen = models.ForeignKey(Finca, on_delete=models.CASCADE)
    diametro = models.CharField(max_length=50)
    altura = models.CharField(max_length=50)
    salud = models.CharField(max_length=50)
    year = models.CharField(max_length=50)

hule/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, reverse
from hule.models import Finca, Parcela, Tree
from usuario.models import Usuario


# Create your views here.
def home(request, usuario_id):
    template = 'hule/home.html'
    context = {
        'fincas': Finca.objects.filter(propietario_id=usuario_id),
        'usuario': usuario_id,
        'usuarios': Usuario.objects.filter(pk=usuario_id),
        'parcela_id': usuario_id,
    }
    return render(request, template, context)


def crear_finca(request, usuario_id):
    if request.method == 'POST':
        nueva_finca = Finca(
            nombre=request.POST['nombre'],
            pais=request.POST['pais'],
            departamento=request.POST['departamento'],
            propietario_id=request.POST['propietario_id'],
        )
        nueva_finca.save()

        return HttpResponseRedirect(reverse('hule:home', kwargs={'usuario_id': nueva_finca.propietario.id}))
    elif request.method == 'GET':
        template = 'hule/crear_finca.html'
        context = {
            'usuario': usuario_id
        }
        return render(request, template, context)
    return HttpResponse('Error al procesarlos datos')


def editar_finca(request, finca_id):
    if request.method == 'POST':
        update_finca = Finca.objects.get(id=finca_id)
        update_finca.nombre = request.POST['nombre']
        update_finca.pais = request.POST['pais']
        update_finca.departamento = request.POST['departamento']
        update_finca.save()

        return HttpResponseRedirect(reverse('hule:home', kwargs={'usuario_id': update_finca.propietario.id}))
    elif request.method == 'GET':
        template = 'hule/editar_finca.html'
        context = {
            'finca': Finca.objects.get(id=finca_id)
        }
        return render(request, template, context)
    return HttpResponse('Error al analisar.')


def borrar_finca(request, finca_id):
    eliminar_finca = Finca.objects.get(id=finca_id)
    eliminar_finca.delete()

    return HttpResponseRedirect(reverse('hule:home', kwargs={'usuario_id': eliminar_finca.propietario.id}))


# ------------------------------------------------------------------------------------------------------------------------------


def home_parcelas(request, usuario_id):
    template = 'hule/home_parcelas.html'
    context = {
        'parcelas': Parcela.objects.all(),
        'usuario_id': usuario_id,
        'cant_parcelas': Parcela.objects.count(),
    }
    return render(request, template, context)


def ver_parcela_de_finca(request, usuario_id, finca_id):
    template = 'hule/ver_parcelas.html'
    context = {
        'parcelas': Parcela.objects.all(),
        'usuario_id': usuario_id,
        'cant_parcelas': Parcela.objects.count(),
        'finca': Finca.objects.get(pk=finca_id),
    }
    return render(request, template, context)


def nueva_parcela(request, usuario_id, finca_id):
        if request.method == 'POST':
            crear_parcela = Finca(
                finca_origen=Finca.objects.get(pk=request.POST['finca_origen']),
                nombre=request.POST['nombre'],
                latitud=request.POST['latitud'],
                longitud=request.POST['longitud'],
            )
            crear_parcela.save()

            return HttpResponseRedirect(reverse('hule:home', kwargs={'usuario_id': usuario_id, 'finca_id': finca_id}))
        elif request.method == 'GET':
            template = 'hule/crear_parcela.html'
            context = {
                'finca': Finca.objects.get(pk=finca_id),
                'usuario': Usuario.objects.get(pk=usuario_id)
            }
            return render(request, template, context)
        return HttpResponse('No se puede guardar!!!')


def editar_parcela(request, usuario_id, finca_id):
    if request.method == 'POST':
        update_parcela = Finca.objects.get(pk=request.POST['finca_origen'])
        update_parcela.nombre = request.POST['nombre']
        update_parcela.latitud = request.POST['latitud']
        update_parcela.longitud = request.POST['longitud']
        update_parcela.save()

        return HttpResponseRedirect(reverse('hule:home', kwargs={'usuario_id': usuario_id, 'finca_id': finca_id}))
    elif request.method == 'GET':
        template = 'hule/editar_parcela.html'
        context = {
            'finca': Finca.objects.get(pk=finca_id),
            'usuario': Usuario.objects.get(pk=usuario_id)
        }
        return render(request, template, context)
    return HttpResponse('Error al analisar.')


def arboles(request):
    cant_arbol = Tree.objects.count()
    print(cant_arbol)
    if cant_arbol < 10:
        return HttpResponse('bien')
    else:
        return HttpResponse('mal')

hule/templates/hule/crear_finca.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Crear</title>
    <style>
        .classuno{
        background: linear-gradient(90deg, rgba(49,230,78,1) 0%, rgba(6,200,133,1) 35%, rgba(0,212,255,1) 100%);
        }

        .classdos{
        width:340px;
        height:440px;
        background:#e6e6e6;
        border-radius:8px;box-shadow:0 0 40px -10px #000;
        margin:calc(50vh - 220px) auto;padding:20px 30px;max-width:calc(100vw - 40px);
        box-sizing:border-box;font-family:'Montserrat',sans-serif;
        position:relative
        }

        .classtres{
        margin:10px 0;
        padding-bottom:10px;
        width:180px;
        color:#78788c;
        border-bottom:3px solid #78788c;
        }

        .classcuatro{
        width:100%;padding:10px;box-sizing:border-box;background:none;
        outline:none;
        resize:none;border:0;
        font-family:'Montserrat',sans-serif;
        transition:all .3s;border-bottom:2px solid #bebed2;
        }

        .classcuatro:focus{border-bottom:2px solid #78788c}

        .classcinco:before{
        content:attr(type);
        display:block;
        margin:28px 0 0;
        font-size:14px;color:#5a5a5a
        }

        .classseis{
        float:right;
        padding:8px 12px;margin:8px 0 0;
        font-family:'Montserrat',sans-serif;
        border:2px solid #78788c;
        background:0;color:#5a5a6e;
        cursor:pointer;
        transition:all .3s
        }

        .classseis:hover{background:#78788c;color:#fff}
    </style>
</head>
<body class="classuno">
    <form class="classdos" action="{% url 'hule:crear_finca' usuario %}" method="POST">{% csrf_token %}
        <h1 class="classtres">Crear Finca</h1>
        <input name="propietario_id" value="{{ usuario }}" hidden>
        <p class="classcinco"><label>Nombre: </label><input class="classcuatro" type="text" name="nombre"></p>
        <p class="classcinco"><label>Pais: </label><input class="classcuatro" type="text" name="pais"></p>
        <p class="classcinco"><label>Departamento: </label><input class="classcuatro" type="text" name="departamento"></p>
        <!--<p><label>Propietario: </label><input type="text" name="propietario"></p>-->
        <p><input class="classseis" type="submit" value="Crear"></p>
    </form>
</body>
</html>

hule/templates/hule/crear_parcela.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Crear</title>
    <style>
                .classuno{
        background: linear-gradient(90deg, rgba(49,230,78,1) 0%, rgba(6,200,133,1) 35%, rgba(0,212,255,1) 100%);
        }

        .classdos{
        width:340px;
        height:500px;
        background:#e6e6e6;
        border-radius:8px;box-shadow:0 0 40px -10px #000;
        margin:calc(50vh - 220px) auto;padding:20px 30px;max-width:calc(100vw - 40px);
        box-sizing:border-box;font-family:'Montserrat',sans-serif;
        position:relative
        }

        .classtres{
        margin:10px 0;
        padding-bottom:10px;
        width:180px;
        color:#78788c;
        border-bottom:3px solid #78788c;
        }

        .classcuatro{
        width:100%;padding:10px;box-sizing:border-box;background:none;
        outline:none;
        resize:none;border:0;
        font-family:'Montserrat',sans-serif;
        transition:all .3s;border-bottom:2px solid #bebed2;
        }

        .classcuatro:focus{border-bottom:2px solid #78788c}

        .classcinco:before{
        content:attr(type);
        display:block;
        margin:28px 0 0;
        font-size:14px;color:#5a5a5a
        }

        .classseis{
        float:right;
        padding:8px 12px;margin:8px 0 0;
        font-family:'Montserrat',sans-serif;
        border:2px solid #78788c;
        background:0;color:#5a5a6e;
        cursor:pointer;
        transition:all .3s
        }

        .classseis:hover{background:#78788c;color:#fff}
    </style>
</head>
<body class="classuno">
    <form class="classdos" action="{% url 'hule:crear_parcela' usuario.pk finca.pk %}" method="POST">{% csrf_token %}
        <h1 class="classtres">Crear Parcela</h1>
        <input class="classcuatro" name="finca_origen" value="{{ finca.nombre }}" disabled/>
        <p class="classcinco"><label>nombre: </label><input class="classcuatro" type="text" name="nombre"></p>
        <p class="classcinco"><label>latitud: </label><input class="classcuatro" type="text" name="latitud"></p>
        <p class="classcinco"><label>longitud: </label><input class="classcuatro" type="text" name="longitud"></p>
        <p><input class="classseis" type="submit" value="Crear"></p>
    </form>
</body>
</html>

hule/templates/hule/editar_finca.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Editar</title>
    <style>

        .classuno{
        background: linear-gradient(90deg, rgba(49,230,78,1) 0%, rgba(6,200,133,1) 35%, rgba(0,212,255,1) 100%);
        }

        .classdos{
        width:340px;
        height:440px;
        background:#e6e6e6;
        border-radius:8px;box-shadow:0 0 40px -10px #000;
        margin:calc(50vh - 220px) auto;padding:20px 30px;max-width:calc(100vw - 40px);
        box-sizing:border-box;font-family:'Montserrat',sans-serif;
        position:relative
        }

        .classtres{
        margin:10px 0;
        padding-bottom:10px;
        width:180px;
        color:#78788c;
        border-bottom:3px solid #78788c;
        }

        .classcuatro{
        width:100%;padding:10px;box-sizing:border-box;background:none;
        outline:none;
        resize:none;border:0;
        font-family:'Montserrat',sans-serif;
        transition:all .3s;border-bottom:2px solid #bebed2;
        }

        .classcuatro:focus{border-bottom:2px solid #78788c}

        .classcinco:before{
        content:attr(type);
        display:block;
        margin:28px 0 0;
        font-size:14px;color:#5a5a5a
        }

        .classseis{
        float:right;
        padding:8px 12px;margin:8px 0 0;
        font-family:'Montserrat',sans-serif;
        border:2px solid #78788c;
        background:0;color:#5a5a6e;
        cursor:pointer;
        transition:all .3s
        }

        .classseis:hover{background:#78788c;color:#fff}

    </style>
</head>
<body class="classuno">
    <form class="classdos" action="{% url 'hule:editar_finca' finca.id %}" method="POST">{% csrf_token %}
        <h1 class="classtres">Editar Finca</h1>
        <p class="classcinco"><label>Nombre:</label><input class="classcuatro" type="text" name="nombre" value="{{ finca.nombre }}"></p>
        <p class="classcinco"><label>Pais: </label><input class="classcuatro" type="text" name="pais" value="{{ finca.pais }}"></p>
        <p class="classcinco"><label>Departamento: </label><input class="classcuatro" type="text" name="departamento" value="{{ finca.departamento }}"></p>
        <p><input class="classseis" type="submit" value="Guardar"></p>
    </form>
</body>
</html>

hule/templates/hule/editar_parcela.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Editar</title>
</head>
<body>
    <form class="classdos" action="{% url 'hule:crear_parcela' usuario.pk finca.pk %}" method="POST">{% csrf_token %}
        <h1 class="classtres">Crear Parcela</h1>
        <input class="classcuatro" name="finca_origen" value="{{ finca.nombre }}" disabled/>
        <p class="classcinco"><label>nombre: </label><input class="classcuatro" type="text" name="nombre"></p>
        <p class="classcinco"><label>latitud: </label><input class="classcuatro" type="text" name="latitud"></p>
        <p class="classcinco"><label>longitud: </label><input class="classcuatro" type="text" name="longitud"></p>
        <p><input class="classseis" type="submit" value="Crear"></p>
    </form>
</body>
</html>

hule/templates/hule/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/litera/bootstrap.min.css" rel="stylesheet" integrity="sha384-D/7uAka7uwterkSxa2LwZR7RJqH2X6jfmhkJ0vFPGUtPyBMF2WMq9S+f9Ik5jJu1" crossorigin="anonymous">
    <meta charset="UTF-8">

    {% if usuarios %}
        {% for usuario in usuarios %}
    <title>Usuario: {{ usuario.nombre }}</title>
        {% endfor %}
    {% endif %}

</head>
<body style="background-image: url(https://k61.kn3.net/F/C/9/F/1/9/EA8.jpg); background-position: center center; background-repeat: no-repeat; background-attachment: fixed; background-size: cover; background-color: #66999;">

<div style="text-align: center; background-color: rgba(43, 38, 21, 0.5); border: 2px solid rgb(163, 151, 111); margin: 1rem; padding: 1rem; border-radius: 30px;">
{% if usuarios %}
    {% for usuario in usuarios %}

    <div style="float: left;">
        <h4 style="color: rgb(227, 217, 182);">Usuario: {{ usuario.nombre }}</h4>
    </div>
<!--<h2 style="color: white;">Id usuario: {{ usuario.id }}</h2>-->
    {% endfor %}
    {% endif %}

    <div style="float: right;">
        <h4><a style="color: rgb(240, 230, 194);" href="{% url 'usuario:inicio' %}">Cerrar Sesion</a></h4>
    </div>

    <div>
        <h4><a style="color: rgb(240, 230, 194);" href="{% url 'hule:crear_finca' usuario  %}">Crear Finca</a></h4>
        <h6 style="text-align: center;"><a style="color: rgb(240, 230, 194);" href="{% url 'hule:home_parcelas' usuario %}">Listado Parcelas</a></h6>
    </div>


</div>

<hr/>

<div>
{% if fincas %}
    {% for finca in fincas %}
    <div style="background-color: rgba(187, 77, 0, 0.75); width: 400px; margin-left: auto; margin-right: auto; margin-top: 10px; border: 2px solid rgb(89, 38, 2); border-radius: 20px;">
    <h2 style="color: rgb(240, 230, 194); text-align: center;">Finca: {{ finca.nombre }}</h2><br>
    <!--<h2> id de la finca {{ finca.id }}</h2>-->
        <h6 style="text-align: center;"><a style="color: rgb(240, 230, 194);" href="{% url 'hule:editar_finca' finca.id %}">Editar Finca</a></h6>
        <h6 style="text-align: center;"><a style="color: rgb(240, 230, 194);" href="{% url 'hule:borrar_finca' finca.id %}">Borrar Finca</a></h6>
        <h6 style="text-align: center;"><a style="color: rgb(240, 230, 194);" href="{% url 'hule:ver_parcela' usuario finca.id %}">Ver Parcelas</a></h6>
        <h6 style="text-align: center;"><a style="color: rgb(240, 230, 194);" href="{% url 'hule:crear_parcela' usuario finca.id %}">Crear Parcela</a></h6>
        <h6 style="text-align: center;"><a style="color: rgb(240, 230, 194);" href="{% url 'hule:editar_parcela' usuario finca.id %}">Editar Parcela</a></h6>
    <hr style="color: rgb(178, 0, 6);" />
    </div>
    {% endfor %}
</div>

    {% else %}
        <h2>Aun no tienes nada registrado.</h2>
{% endif %}

</body>
</html>

hule/templates/hule/home_parcelas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Parcelas</title>
    <style>
        .classuno{
        background: linear-gradient(90deg, rgba(232,6,37,1) 0%, rgba(93,47,49,1) 35%, rgba(70,0,11,1) 100%);
        }

        .classdos{
        color: white;
        }
    </style>
</head>
<body class="classuno">
<h4><a style="color: rgb(240, 230, 194);" href="{% url 'hule:home' usuario_id %}">Regresar</a></h4>
{% if parcelas %}
{% for parcela in parcelas %}

<div style="background-color: rgba(187, 77, 0, 0.75); width: 400px; margin-left: auto; margin-right: auto; margin-top: 10px; border: 2px solid rgb(89, 38, 2); border-radius: 20px;">
<ul class="classdos">{{ parcela.nombre }}</ul>
</div>

{% endfor %}
{% endif %}
</body>
</html>

hule/templates/hule/ver_parcelas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Parcelas</title>
</head>
<body>
<div>
{% if parcelas %}
    {% for parcela in parcelas %}
    <div style="background-color: rgba(187, 77, 0, 0.75); width: 400px; margin-left: auto; margin-right: auto; margin-top: 10px; border: 2px solid rgb(89, 38, 2); border-radius: 20px;">
    <h2 style="color: rgb(240, 230, 194); text-align: center;">Finca: {{ parcela.nombre }}</h2><br>
    <!--<h2> id de la finca {{ finca.id }}</h2>-->
        <h6 style="text-align: center;"><a style="color: rgb(240, 230, 194);" href="{% url 'hule:editar_parcela' usuario_id finca.id %}">Editar</a></h6>
        <h6 style="text-align: center;"><a style="color: rgb(240, 230, 194);" href="">Borrar</a></h6>
        <h6 style="text-align: center;"><a style="color: rgb(240, 230, 194);" href="#">Ver Parcelas</a></h6>
        <h6 style="text-align: center;"><a style="color: rgb(240, 230, 194);" href="">Crear Parcela</a></h6>
        <h6 style="text-align: center;"><a style="color: rgb(240, 230, 194);" href="">Editar Parcela</a></h6>
    <hr style="color: rgb(178, 0, 6);" />
    </div>
    {% endfor %}
    {% endif %}
</div>
</body>
</html>