examen/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuario/', include('usuario.urls')),
    path('home/', include('hule.urls')),
]

hule/urls.py
from django.urls import path
from hule import views


app_name = 'hule'


urlpatterns = [
    path('home/<int:usuario_id>/', views.home, name='home'), # ve todas sus fincas que le corresponden

    path('crear/<int:usuario_id>/', views.crear_finca, name='crear_finca'),     # crea una su finquita
    path('editar/<int:finca_id>/', views.editar_finca, name='editar_finca'),    # edita su finquita
    path('borrar/<int:finca_id>/', views.borrar_finca, name='borrar_finca'),    # elimina su finquita

    path('home-p/<int:usuario_id>/', views.home_parcelas, name='home_parcelas'),    # ve todas sus parcelas
    path('ver/<int:usuario_id>/<int:finca_id>/', views.ver_parcela_de_finca, name='ver_parcela'),   # ver parcelas
    path('crear-p/<int:usuario_id>/<int:finca_id>/', views.nueva_parcela, name='crear_parcela'),    # crear parcela
    path('editar-p/<int:usuario_id>/<int:finca_id>/', views.editar_parcela, name='editar_parcela'),    # crear parcela

    path('arboles/', views.arboles, name='arboles'),
]

usuario/urls.py
from django.urls import path
from usuario import views


app_name = 'usuario'


urlpatterns = [
    path('registro/', views.crear_usuario, name='registro'),
    path('inicio/', views.inicio_sesion, name='inicio'),
]

usuario/models.py
from django.db import models


# Create your models here.
class Usuario(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    telefono = models.CharField(max_length=25, unique=True)
    correo = models.CharField(max_length=50, unique=True)
    clave = models.CharField(max_length=50)
    permiso = models.CharField(max_length=1)

    def __str__(self):
        return self.nombre + ', ' + self.clave + ', ' + self.correo

usuario/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, reverse
from usuario.models import Usuario


# Create your views here.
def crear_usuario(request):
    if request.method == 'POST':
        nuevo_usuario = Usuario(
            nombre=request.POST['nombre'],
            apellido=request.POST['apellido'],
            telefono=request.POST['telefono'],
            correo=request.POST['correo'],
            clave=request.POST['clave'],
            permiso=request.POST['permiso'],
        )
        nuevo_usuario.save()

        return HttpResponseRedirect(reverse('usuario:inicio'))
    elif request.method == 'GET':
        template = 'usuario/crear_usuario.html'
        return render(request, template)
    return HttpResponse('Error en la solicitud.')


def inicio_sesion(request):
    if request.method == 'POST':
        try:
            usuario = Usuario.objects.get(correo=request.POST['correo'], clave=request.POST['clave'])
        except Usuario.DoesNotExist:
            return HttpResponseRedirect(reverse('usuario:inicio'))

        return HttpResponseRedirect(reverse('hule:home', kwargs={'usuario_id': usuario.id}))
    elif request.method == 'GET':
        template = 'usuario/inicio_usuario.html'
        return render(request, template)
    return HttpResponse('Error al procesar los datos.')


    """while True:
        error = 0

        usuario = input("Nombre de usuario ")
        pass1 = input("contrasena ")
        pass2 = input("repite contrasena ")

        if len(usuario) < 8 or len(usuario) > 12:
            print("la longitud del usuario no es correcta")
            error = 1
        if len(pass1) < 10:
            print("la longitud de la contrasena no es correcta")
            error = 1
        if not re.search('[0-9]', pass1):
            print("la contrasena tiene que tener al menos un numero")
            error = 1
        if pass1 != pass2:
            print("las contrasenas no son iguales")
            error = 1

        if error == 0:
            print("OK")
            break"""

usuario/templates/usuario/crear_usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registro</title>
        <style>
                .classuno{
        background: linear-gradient(90deg, rgba(49,230,78,1) 0%, rgba(6,200,133,1) 35%, rgba(0,212,255,1) 100%);
        }

        .classdos{
        width:340px;
        height:740px;
        background:#e6e6e6;
        border-radius:8px;box-shadow:0 0 40px -10px #000;
        margin:calc(50vh - 220px) auto;padding:20px 30px;max-width:calc(100vw - 40px);
        box-sizing:border-box;font-family:'Montserrat',sans-serif;
        position:relative
        }

        .classtres{
        margin:10px 0;
        padding-bottom:10px;
        width:180px;
        color:#78788c;
        border-bottom:3px solid #78788c;
        }

        .classcuatro{
        width:100%;padding:10px;box-sizing:border-box;background:none;
        outline:none;
        resize:none;border:0;
        font-family:'Montserrat',sans-serif;
        transition:all .3s;border-bottom:2px solid #bebed2;
        }

        .classcuatro:focus{border-bottom:2px solid #78788c}

        .classcinco:before{
        content:attr(type);
        display:block;
        margin:28px 0 0;
        font-size:14px;color:#5a5a5a
        }

        .classseis{
        float:right;
        padding:8px 12px;margin:8px 0 0;
        font-family:'Montserrat',sans-serif;
        border:2px solid #78788c;
        background:0;color:#5a5a6e;
        cursor:pointer;
        transition:all .3s
        }

        .classseis:hover{background:#78788c;color:#fff}
    </style>
</head>
<body class="classuno">
    <form class="classdos" action="{% url 'usuario:registro' %}" method="POST">{% csrf_token %}
        <h1 class="classtres">Crear Cuenta.</h1>
        <p class="classcinco"><label>Nombre: </label><input class="classcuatro" type="text" name="nombre"></p>
        <p class="classcinco"><label>Apellido: </label><input class="classcuatro" type="text" name="apellido"></p>
        <p class="classcinco"><label>Telefono: </label><input class="classcuatro" type="text" name="telefono"></p>
        <p class="classcinco"><label>Correo: </label><input class="classcuatro" type="text" name="correo"></p>
        <p class="classcinco"><label>Clave: </label><input class="classcuatro" type="password" name="clave"></p>
        <p class="classcinco" hidden><label hidden>Permiso: </label><input type="text" name="permiso" value="0" hidden></p>
        <h4><a style="color: black;" href="{% url 'usuario:inicio' %}"><h6>Ya tienes una cuenata.</a></h4>
        <p><input class="classseis" type="submit" value="Guardar"></p>
    </form>
</body>
</html>

usuario/templates/usuario/inicio_usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inicio</title>

    <style>
        @import url('https://rsms.me/inter/inter-ui.css');
::selection {
  background: #2D2F36;
}
::-webkit-selection {
  background: #2D2F36;
}
::-moz-selection {
  background: #2D2F36;
}
body {
  background: white;
  font-family: 'Inter UI', sans-serif;
  margin: 0;
  padding: 20px;
}
.page {
  background: #e2e2e5;
  display: flex;
  flex-direction: column;
  height: calc(100% - 40px);
  position: absolute;
  place-content: center;
  width: calc(100% - 40px);
}
@media (max-width: 767px) {
  .page {
    height: auto;
    margin-bottom: 20px;
    padding-bottom: 20px;
  }
}
.container {
  display: flex;
  height: 320px;
  margin: 0 auto;
  width: 640px;
}
@media (max-width: 767px) {
  .container {
    flex-direction: column;
    height: 630px;
    width: 320px;
  }
}
.left {
  background: white;
  height: calc(100% - 40px);
  top: 20px;
  position: relative;
  width: 50%;
}
@media (max-width: 767px) {
  .left {
    height: 100%;
    left: 20px;
    width: calc(100% - 40px);
    max-height: 270px;
  }
}
.login {
  font-size: 50px;
  font-weight: 900;
  margin: 50px 40px 40px;
}
.eula {
  color: #999;
  font-size: 14px;
  line-height: 1.5;
  margin: 40px;
}
.right {
  background: #474A59;
  box-shadow: 0px 0px 40px 16px rgba(0,0,0,0.22);
  color: #F1F1F2;
  position: relative;
  width: 50%;
}
@media (max-width: 767px) {
  .right {
    flex-shrink: 0;
    height: 100%;
    width: 100%;
    max-height: 350px;
  }
}
svg {
  position: absolute;
  width: 320px;
}
path {
  fill: none;
  stroke: url(#linearGradient);;
  stroke-width: 4;
  stroke-dasharray: 240 1386;
}
.form {
  margin: 40px;
  position: absolute;
}
label {
  color:  #c2c2c5;
  display: block;
  font-size: 14px;
  height: 16px;
  margin-top: 20px;
  margin-bottom: 5px;
}
input {
  background: transparent;
  border: 0;
  color: #f2f2f2;
  font-size: 20px;
  height: 30px;
  line-height: 30px;
  outline: none !important;
  width: 100%;
}
input::-moz-focus-inner {
  border: 0;
}
#submit {
  color: #707075;
  margin-top: 40px;
  transition: color 300ms;
}
#submit:focus {
  color: #f2f2f2;
}
#submit:active {
  color: #d0d0d2;
}
</style>

</head>
<body class="classuno">
<div class="page">
        <div class="container">
          <div class="left">
            <div class="login">Inicio de Sesion.</div>
            <div class="eula">Un arbol, Una vida. <h3><a style="color: black;" href="{% url 'usuario:registro' %}">Crear Cuenta</a></h3>
            </div>
          </div>
          <div class="right">
            <svg viewBox="0 0 320 300">
              <defs>
                <linearGradient
                                inkscape:collect="always"
                                id="linearGradient"
                                x1="13"
                                y1="193.49992"
                                x2="307"
                                y2="193.49992"
                                gradientUnits="userSpaceOnUse">
                  <stop
                        style="stop-color:#ff00ff;"
                        offset="0"
                        id="stop876" />
                  <stop
                        style="stop-color:#ff0000;"
                        offset="1"
                        id="stop878" />
                </linearGradient>
              </defs>
              <path d="m 40,120.00016 239.99984,-3.2e-4 c 0,0 24.99263,0.79932 25.00016,35.00016 0.008,34.20084 -25.00016,35 -25.00016,35 h -239.99984 c 0,-0.0205 -25,4.01348 -25,38.5 0,34.48652 25,38.5 25,38.5 h 215 c 0,0 20,-0.99604 20,-25 0,-24.00396 -20,-25 -20,-25 h -190 c 0,0 -20,1.71033 -20,25 0,24.00396 20,25 20,25 h 168.57143" />
            </svg>
            <div class="form" >
                <form action="{% url 'usuario:inicio' %}" method="POST">{% csrf_token %}
                    <p for="email"><label>Correo: </label><input type="email" id="email" name="correo" placeholder="______________________"></p>
                    <p type="password"><label>Clave: </label><input type="password" id="password" name="clave" placeholder="______________________"></p>
                    <p><input id="submit" type="submit" value="Inicio"></p>
            </div>
          </div>
        </div>
      </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.2.0/anime.min.js"></script>
<script>
var current = null;
document.querySelector('#email').addEventListener('focus', function(e) {
  if (current) current.pause();
  current = anime({
    targets: 'path',
    strokeDashoffset: {
      value: 0,
      duration: 700,
      easing: 'easeOutQuart'
    },
    strokeDasharray: {
      value: '240 1386',
      duration: 700,
      easing: 'easeOutQuart'
    }
  });
});
document.querySelector('#password').addEventListener('focus', function(e) {
  if (current) current.pause();
  current = anime({
    targets: 'path',
    strokeDashoffset: {
      value: -336,
      duration: 700,
      easing: 'easeOutQuart'
    },
    strokeDasharray: {
      value: '240 1386',
      duration: 700,
      easing: 'easeOutQuart'
    }
  });
});
document.querySelector('#submit').addEventListener('focus', function(e) {
  if (current) current.pause();
  current = anime({
    targets: 'path',
    strokeDashoffset: {
      value: -730,
      duration: 700,
      easing: 'easeOutQuart'
    },
    strokeDasharray: {
      value: '530 1386',
      duration: 700,
      easing: 'easeOutQuart'
    }
  });
});
</script>

</body>
</html>